on:
  push:
    tags:
      - '*'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Grab tag name
        uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Create release note
        run: ./build-release-note.sh ${{ github.ref }} > NOTE.md
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: NOTE.md
          draft: false
          prerelease: false
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Release to bintray
        run: ./release-ci.sh ${{ steps.tagName.outputs.tag }}
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
      - name: Release to Maven
        run: ./release-maven-central.sh
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
