on:
  push:
    tags:
      - '*'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Release to bintray
        run: ./release-ci.sh
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
      - name: Grab tag name
        uses: olegtarasov/get-tag@v2
        id: tagName
      - uses: peter-evans/repository-dispatch@v1.1.1
        with:
          token: ${{ secrets.ORG_PUBLIC_REPO_WORKFLOW_TRIGGERING }}
          repository: http4k/http4k-connect
          event-type: connect-release
          client-payload: '{"version": "${{ steps.tagName.outputs.tag }}"}'
